base_url = "https://nova-me.github.io/"
title = "zola-everforest"
description = "inspired by everforest"
default_language = "en"
compile_sass = false
minify_html = true
generate_feed = true

taxonomies = [{ name = "tags" }]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "NOVA-ME"
favicon = "favicon.ico"
image = ""
list_pages = false
twitter_card = true

header_nav = [
  { name = "/home/", url = "/" },
  { name = "/about/", url = "/about" },
  { name = "/blog/", url = "/blog" },
]
